# ===== Conexión a PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/underBase
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Hibernate / JPA =====
# Esquema por defecto para todas las entidades
spring.jpa.properties.hibernate.default_schema=modeloventas

# Recrea las tablas en cada arranque y las borra al cerrar
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ===== JSON (Parte 3) =====
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Argentina/Buenos_Aires